### ISSUE TITLE
Items spin forever in water

### ISSUE THREAD

**Issue by YoshiRulz** [CreativeMD/ItemPhysicLite#17]
I don't know if this is intended but it looks bad, especially on 2D items.

MC 1.20.4, Fabric API 0.95.1, CreativeCore 2.11.16, ItemPhysic Lite 1.6.3

**Comment by CreativeMD** [comment]
Actually that is intended as long as they float, once they hit the ground it should stop. They should only rotate slowly though.

**Comment by CreativeMD** [comment]
Will close this issue for now. Don't see any issue here.

**Comment by YoshiRulz** [comment]
You're telling me this is intentional?

https://github.com/CreativeMD/ItemPhysicLite/assets/13409956/ca744b41-41b5-4463-8c49-6fd94ff6760a

Something like `angVel *= 0.99` each tick would make it look less out-of-place IMO.

**Comment by CreativeMD** [comment]
Yes that is intentional and there is no angular motion that's why it cannot slow down over time. You can modify the overall speed, but that's it. This is a very basic mod and adding more calculations would mean a deeper change in how items work (which would affect server side as well).
