### ISSUE TITLE
z-fighting

### ISSUE THREAD

**Issue by PukPukov** [CreativeMD/ItemPhysicLite#18]
If lying items are colliding they will z-fight. It looks very ugly.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue. Sorry for responding that late. Furthermore this fix will also be added to the Full version of ItemPhysic.

**Comment by PukPukov** [comment]
Will it be released for fabric 1.20.4 on modrinth/curseforge? I tried to compile myself, but im not very in modding and build fails not finding forge plugin in any repository.

**Comment by CreativeMD** [comment]
New version for 1.20.4 have been released now.
