### ISSUE TITLE
[Forge - 1.19.2]: No config options

### ISSUE THREAD

**Issue by SiverDX** [CreativeMD/ItemPhysicLite#19]
See

![image](https://github.com/CreativeMD/ItemPhysicLite/assets/22003703/fa8ab9f0-555a-4061-be45-da009b1ea410)

**Comment by CreativeMD** [comment]
The version for 1.19.2 is outdated and I do not support it anymore. Sorry, but I cannot help you there. Maybe you can change the configuration via the file, should be in your config folder called `itemphysic-lite-client.json`.

**Comment by SiverDX** [comment]
config was introduced after 1.19.3 so no dice
https://github.com/CreativeMD/ItemPhysicLite/commit/5d30d1e818016a6d56a8a6d5da6a328e0b27565f

i slapped the fixed code into a patchwork mod for my modpack so its w/e for me at this point
