### ISSUE TITLE
On server dropped items are invisible

### ISSUE THREAD

**Issue by Deykii** [CreativeMD/ItemPhysicLite#22]
When I play on a server all items I drop turning invisible. Is it normal? Is there a way to fix it?

**Comment by CreativeMD** [comment]
That should not happen. Are you sure this is caused by ItemPhysicLite? Have you removed the mod to see if then works?

**Comment by Deykii** [comment]
> That should not happen. Are you sure this is caused by ItemPhysicLite? Have you removed the mod to see if then works?

Oh, for real? Um, okay, I'll take a look, but I don't have any mod that can affect on dropped items

**Comment by CreativeMD** [comment]
Might be a vanilla bug?

**Comment by Deykii** [comment]
> Might be a vanilla bug?

Idk, it just turning invisible on servers only :0

**Comment by CreativeMD** [comment]
Even without ItemPhysicLite installed?

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. If the issue persists just reply here.
