### ISSUE TITLE
[Bug] Buried Items On Specific Blocks

### ISSUE THREAD

**Issue by Fyoncle** [CreativeMD/ItemPhysicLite#24]
When you throw items into specific blocks, they get buried and never visible, not sure if its problem of this mod, but yea.

https://github.com/CreativeMD/ItemPhysicLite/assets/63975256/fb27468e-2ac2-4966-a791-14e1576847c6

That's how it looks like, don't think its only happens with modded blocks, but also other specific blocks that i forgot yet.

**Comment by CreativeMD** [comment]
Hey, sorry for not responding earlier. The newest version of ItemPhysic and ItemPhysicLite has a new option called blockRequireOffset you can use that to add different variants of soul sand to fix this issue. You can get to this setting by using the command /cmdclientconfig. Unfortunately this feature is only available in 1.21. I do not have the time at the moment to port it back.

**Comment by Fyoncle** [comment]
> Hey, sorry for not responding earlier. The newest version of ItemPhysic and ItemPhysicLite has a new option called blockRequireOffset you can use that to add different variants of soul sand to fix this issue. You can get to this setting by using the command /cmdclientconfig. Unfortunately this feature is only available in 1.21. I do not have the time at the moment to port it back.

Oh i had this in 1.20.1, me sad ;(

**Comment by Fyoncle** [comment]
> Hey, sorry for not responding earlier. The newest version of ItemPhysic and ItemPhysicLite has a new option called blockRequireOffset you can use that to add different variants of soul sand to fix this issue. You can get to this setting by using the command /cmdclientconfig. Unfortunately this feature is only available in 1.21. I do not have the time at the moment to port it back.

Will this ever be backported by any chance if you would have time? or will it never be backported.

**Comment by CreativeMD** [comment]
Alright. Released it for 1.20.1 as well. Still I recommend to update to 1.21 because 1.20 is lacking a few features already.

**Comment by Fyoncle** [comment]
> Alright. Released it for 1.20.1 as well. Still I recommend to update to 1.21 because 1.20 is lacking a few features already.

I won't update. It lacking many mods i like, plus my modpack is for 1.20.1 and it will be a pain to port. But thank you so much for making my life easier by this backport! xD ❤️
