### ISSUE TITLE
invisible items using item physics 

### ISSUE THREAD

**Issue by oksTDY** [CreativeMD/ItemPhysicLite#26]
when i drop items using the mod instead of it laying on the floor it is invisible, how do i fix this? 
![image_2024-07-30_003853620](https://github.com/user-attachments/assets/88a6a4d7-00b4-49dc-8172-e2d3ca8d9100)

**Comment by CreativeMD** [comment]
Are you sure this issue is related to ItemPhysicLite. What minecraft version are you using? What other mods are installed?

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity.
