### ISSUE TITLE
I can't see my items when they are in snow

### ISSUE THREAD

**Issue by SkyAdri-mc** [CreativeMD/ItemPhysicLite#3]
Jepp, this is a problem.

**Comment by CreativeMD** [comment]
Which version are you using? This should not be a thing.

**Comment by CreativeMD** [comment]
Will close this issue for now. If it still persists just post the version here.

**Comment by Ihsan101** [comment]
This issue is on 1.8.9 version. It is still in version 1.3 so that might be why.
