### ISSUE TITLE
[Suggestion] Configuration file

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/ItemPhysicLite#4]
It would be nice to have the same level of client configuration that Full provides, to control rotation speed and such.

**Comment by CreativeMD** [comment]
Sorry, but I don't want to make it depend on CreativeCore.

**Comment by ChloeDawn** [comment]
Is it safe to use Full client-side-only then if all if the other features are disabled?

**Comment by CreativeMD** [comment]
Not sure what safe means, but you will have troubles on a vanilla server. Not huge ones though (if you remove all swimming and burning items it might work just fine).
