### ISSUE TITLE
Items occationally invisible

### ISSUE THREAD

**Issue by BrainStone** [CreativeMD/ItemPhysicLite#6]
Around 10% of items that drop are invisible.

I can pick them up, players without the mod can see them (don't have other players with that mod to cross reference if it's the same items or if it's different for everybody) just fine.

**Comment by CreativeMD** [comment]
That is very weird. Not sure if this issue is related to this mod though, how are things if this mod is not installed?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists just post more information here.
