### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by jgeekw** [CreativeMD/ItemPhysicLite#7]
Getting this error when trying to load a server with this mod:

Mod File: ItemPhysicLite_v1.4.7_mc1.16.4.jar
	Failure message: ItemPhysic Lite has class loading errors
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.4.0
	Mod Issue URL: https://github.com/CreativeMD/ItemPhysicLite/issues
	Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER

**Comment by CreativeMD** [comment]
Can you please send me the entire crash-report? Also if you are using Minecraft 1.16.5 you should use the newest version of ItemPhysic lite.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists just post the crash-report here.

**Comment by DrUltraLux** [comment]
I am getting the same crash. My log here. 

[crash-2021-10-27_12.28.53-fml.txt](https://github.com/CreativeMD/ItemPhysicLite/files/7422465/crash-2021-10-27_12.28.53-fml.txt)

**Comment by CreativeMD** [comment]
ItemPhysic lite cannot be installed on server side. Use ItemPhysic Full for that.
