### ISSUE TITLE
Items appear below snow, and arent visible to players. 

### ISSUE THREAD

**Issue by Ihsan101** [CreativeMD/ItemPhysicLite#8]
![image](https://user-images.githubusercontent.com/96698644/147464973-bb969b6f-d5ab-4636-a0ac-6ab2f067ae94.png)

This happens on version 1.8, might be because it is still on version 1.3, while other versions are on 1.4.x

**Comment by CreativeMD** [comment]
Should be fixed in the newer versions. I don't support 1.8 anymore, sorry.
